FROM node:22-alpine AS builder
WORKDIR /app
COPY src/product-service/package*.json ./
RUN npm ci --only=production

FROM node:22-alpine
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY src/product-service/ .
EXPOSE 3002
CMD ["node", "server.js"]