FROM node:22-alpine AS builder
WORKDIR /app
COPY src/order-service/package*.json ./
RUN npm ci --only=production

FROM node:22-alpine
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY src/order-service/ .
EXPOSE 3003
CMD ["node", "server.js"]