FROM node:22-alpine AS builder
WORKDIR /app
COPY src/user-service/package*.json ./
RUN npm install --omit=dev

FROM node:22-alpine
WORKDIR /app
COPY --from=builder /app/node_modules ./node_modules
COPY src/user-service/ .
EXPOSE 3001
CMD ["node", "server.js"]