apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - user-deployment.yaml
  - product-deployment.yaml
  - order-deployment.yaml
  - notification-deployment.yaml
  - frontend-deployment.yaml